# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - release
  - devel

r_packages:
  - lintr
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
