NOTE_INSTALL_PACKAGE = "Installing %s %s"
NOTE_INSTALL_PACKAGE_VERSION = "at version %s"
NOTE_PACKAGE_NOT_INSTALLED = "NOTE: %s is not currently installed."
NOTE_BAD_PACKAGE_VERSION = "NOTE: %s is current installed at version %s which is not sufficient."
ERROR_NO_PACKAGE_EXISTS = "ERROR: No version exists for %s which meets requirements."
ERROR_OTHER_FAILURE = "ERROR: Requirement %s could not be satisified for some reason."
ERROR_FAILURE_COUNT = "There were %d package(s) which could not be installed."

REQ_FILE_EXIST_ERR = "The specified requirements file, %s, does not exist"
REQ_FILE_EMPTY_ERR = "The requirements file %s is empty."
REQ_FILE_RESOLUTION_ERR = "Not all requirements are allowed: %s"
REQ_FILE_INVALID_COMP = "Invalid requirement: '%s'\n%s is not a valid operator. Did you mean %s ?"
REQ_FILE_DUPLICATE_REQ = "Double requirement given: %s (line %d) (already in %s, name='%s')\n"

AUTO_GEN_COMMENTS = c(
  "# Generated by requirements::generate_requirements().  Modify as needed.",
  "# Install using requirements::install_requirements().",
  ""
)
